/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    copy: typeof import('./src/components/VisitorTrends copy.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    DailySales: typeof import('./src/components/DailySales.vue')['default']
    DailyVisitor: typeof import('./src./src/components/DailySales.vueault']
    DailyVisitors: typeof import('./src/components/DailyVisitors.vue')['default']
    DeviceInstallOverview: typeof import('./src/components/DeviceInstallOverview.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VisitorsSales: typeof import('./src/components/VisitorsSales.vue')['default']
    VisitorTrends: typeof import('./src/components/VisitorTrends.vue')['default']
  }
}
